// Labels used by the "ARRÊTER" button when repeatedly clicked.
export const CORE_BUTTON_LABELS: string[] = [
  'ARRÊTER',
  'VRAIMENT ?',
  'NON',
  'ARRÊTE',
  'STOP',
  'NON NON',
  "S'IL TE PLAÎT",
  'ARRÊTE VRAIMENT',
  'ENCORE ?',
  'BON',
  "D'ACCORD CLIQUE",
  'SI TU INSISTES',
  'JE SUIS FATIGUÉ',
  'TU ES FATIGANT.E',
  'SÉRIEUX ?',
  'MAIS POURQUOI',
  'LÂCHE-MOI',
  '...',
  '*soupir*',
  'IMPOSSIBLE',
  'RIEN NE SE PASSE',
  'TU VOIS BIEN',
  "C'EST UN PIÈGE",
  'PAS UN PIÈGE EN FAIT',
  'LITTÉRALEMENT RIEN',
  'ENCORE UN',
  'ET UN DE PLUS',
  "TU T'EN LASSES PAS ?",
  'NON ?',
  "D'ACCORD.",
  'COMME TU VEUX',
  'ON CONTINUE',
  'OK CHEF',
  'JE SUIS UN BOUTON',
  "C'EST TOUT",
  "RIEN D'AUTRE",
  'NON VRAIMENT',
  'TU PEUX PARTIR',
  'OU RESTER',
  '¯\\_(ツ)_/¯',
  'CLIC',
  'CLAC',
  'CLIC.',
  'ARRÊTER ENFIN',
  'JAMAIS.',
  "POURQUOI T'ES LÀ",
  'TU AS UNE VIE ?',
  'OUI VISIBLEMENT',
  'BON BAH VOILÀ',
];
