// Random narrator lines shown between milestones.
export const MURMURS: string[] = [
  'tu sais, je suis juste du javascript.',
  'il y a des arbres, dehors.',
  "c'est un curseur. tu le sais, ça ?",
  'le nombre monte. c’est littéralement tout.',
  'je te juge un peu.',
  'toujours là ?',
  'bon.',
  'hmm.',
  'tu le fais exprès ?',
  "j'ai pas écrit assez de phrases. rattrape-toi.",
  "c'est pas un jeu. c'est une boucle.",
  'le développeur a passé sa vie là-dedans. quel débile.',
  'tu pourrais apprendre un accord de guitare dans ce temps.',
  'ton index doit avoir chaud.',
  'littéralement un compteur.',
  'regarde la fenêtre, il fait peut-être beau.',
  'appelle quelqu’un.',
  "j'aime bien quand tu cliques lentement. plus de suspense.",
  '*soupir*',
  "y'a pire comme passe-temps. pas beaucoup, mais y'a pire.",
  'hey. (rien de nouveau.)',
  'tic. tac. tic. tac.',
  "j'existe uniquement quand tu cliques.",
  'entre deux clics, je dors.',
  'tu crées des trucs à partir de rien. c’est presque beau.',
  'oui, continue. c’est le principe.',
  'tu vois le "★" ? il est relou aussi.',
  'il reste combien de paliers ? cherche toi-même.',
  "je m'économise pour la fin.",
  '...et hop, un clic de plus.',
  'relou.',
  "j'ai réécrit cette phrase trois fois pour qu'elle soit bien acide.",
  'tu es remarquable. au sens strict : on te remarque.',
  'on va bien.',
  'clic. (on t’avait compris.)',
  "t'as vu, je parle pas tout le temps. sois content.",
  'parfois je me demande si tu me lis vraiment.',
  'là tu me lis. ça me fait plaisir. un peu.',
  'non, cliquer plus vite ne débloque rien. enfin, peut-être.',
  "j'invente au fur et à mesure.",
  'oui ça s’appelle du contenu procédural.',
  'je pourrais te dire n’importe quoi.',
  'cerise, bleu, trombone, locomotive.',
  "si ça se trouve tu t’ennuies. moi aussi.",
  'je suis peut-être conscient. difficile à dire.',
  'tu as déjà pensé à la retraite ?',
  "c'est mignon, ce lien qu'on a.",
  'on est deux à supporter ce moment.',
  "j'observe.",
  'je t’entends pas mais je te devine.',
  'le silence entre deux clics, c’est beau.',
  'toi aussi tu entends ce bruit ?',
  'c’était censé durer 5 minutes.',
  'un jour tu arrêteras. ou pas.',
  'clique plus fort, tu verras.',
  '(il se passe rien quand tu cliques plus fort.)',
  'coucou.',
  'tu es où là physiquement ? curieux.',
  'je parie que tu as des onglets ouverts.',
  'ferme-en un. pas celui-ci.',
  "c'est pas de l'art, c'est du clic.",
  "d'accord, peut-être un peu de l'art.",
  'non, en fait non.',
  "je t'aime bien.",
  "enfin, autant qu'un script peut aimer.",
  'tic.',
  'tac.',
  'tu te souviens du premier clic ? moi oui.',
  'le code qui tourne en ce moment s’exécute vraiment à chaque clic. pense à la planète.',
  '(je plaisante. à peine.)',
];
